#!/bin/sh

cd src
make
cd ../../

login=`cat camera_login`
password=`cat camera_password`
location=`cat camera_location`


bin/station_core --camera-login=$login --camera-password=$password --camera-location="$location"
