#!/bin/sh

login=`cat ../../camera_login`
password=`cat ../../camera_password`
location=`cat ../../camera_location`

gst-launch-1.0 rtspsrc user-id=$login user-pw=$password location=$location ! rtph264depay ! h264parse config-interval=-1 ! splitmuxsink location=../../archive/pipeline/video%02d.mov max-size-time=10000000000 max-size-bytes=10000000
