#!/bin/sh

login=`cat ../../camera_login`
password=`cat ../../camera_password`
location=`cat ../../camera_location`

gst-launch-1.0 rtspsrc user-id=$login user-pw=$password location=$location ! rtph264depay ! h264parse ! rtph264pay ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! autovideosink
